service: lambda-notifier

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParametersByPath
        - ssm:GetParameter
      Resource: '*'

plugins:
  - serverless-offline
  - serverless-plugin-monorepo

package:
  exclude:
    - .git/**
    - .gitignore
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
      - schedule:
          rate: rate(1 day)
          enabled: true
