version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - $APP_PORT:$APP_PORT
      - 9229:9229
    expose:
      - $APP_PORT
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DB_HOSTNAME: database
      DB_PORT: '5432'
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
    depends_on:
      - database
    restart: always

  database:
    container_name: db
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050

volumes:
  postgresdb:
