version: '3.8'

services:
  clinic:
    container_name: clinic
    build:
      context: .
      dockerfile: ./packages/clinic/Dockerfile
    volumes:
      - ./packages/clinic:/app/packages/clinic
      - /app/packages/clinic/node_modules
      - /app/packages/clinic/dist/
    ports:
      - $CLINIC_PORT:$CLINIC_PORT
    env_file:
      - config.env
      - dbconn.env
    environment:
      APP_PORT: $CLINIC_PORT
      PROFILE_GRPC_URL: $PROFILE_GRPC_URL
      CLINIC_GRPC_URL: $CLINIC_GRPC_URL
    depends_on:
      - database
    restart: always

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    volumes:
      - ./packages/auth:/app/packages/auth
      - /app/packages/auth/node_modules
      - /app/packages/auth/dist
    ports:
      - $AUTH_PORT:$AUTH_PORT
    env_file:
      - config.env
      - dbconn.env
    environment:
      APP_PORT: $AUTH_PORT
      PROFILE_GRPC_URL: $PROFILE_GRPC_URL
      AUTH_GRPC_URL: $AUTH_GRPC_URL
      CLINIC_GRPC_URL: $CLINIC_GRPC_URL
    depends_on:
      - database
    restart: always

  profile:
    container_name: profile
    build:
      context: .
      dockerfile: ./packages/profile/Dockerfile
    volumes:
      - ./packages/profile:/app/packages/profile
      - /app/packages/profile/node_modules
      - /app/packages/profile/dist
    ports:
      - $PROFILE_PORT:$PROFILE_PORT
    env_file:
      - config.env
      - dbconn.env
    environment:
      APP_PORT: $PROFILE_PORT
      PROFILE_GRPC_URL: $PROFILE_GRPC_URL
    depends_on:
      - database
    restart: always

  database:
    container_name: db
    image: postgres:11.2-alpine
    restart: always
    env_file:
      - dbconn.env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
