version: '3.7'

services:
  global:
    container_name: main
    build: ./packages/app
    volumes:
      - ./packages/app:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      APP_PORT: '8080'
      DB_HOSTNAME: database
      DB_PORT: '5432'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: random
      POSTGRES_DB: med
      JWT_SECRET: sfghgyrv
      SALT: 10
      RUN_MIGRATIONS: 'true'
    working_dir: '/app'
    depends_on:
      - database
    command: yarn start:dev
    restart: always

  database:
    container_name: db
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: random
      POSTGRES_DB: med
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050

volumes:
  postgresdb:
