version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    expose:
      - ${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DB_HOSTNAME: mysql
      DB_PORT: '3306'
      DB_USER: user
      DB_PASSWORD: user
      DB_NAME: med
    networks:
      - webnet
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: randompassword
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: med
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - webnet
volumes:
  mysqldb:
networks:
  webnet:
